version: '3.8'

services:
  erp-app:
    container_name: erp-system
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost:3000/api/health", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - erp-network

  # 可選: Nginx 反向代理
  nginx:
    container_name: erp-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/nginx/certificates
      - ./nginx/www:/var/www/html
    depends_on:
      - erp-app
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge 